Add files via upload
Still trying to see what errors I've gotten here.

Assets\Scripts\NPC Brain.cs(309,5): error CS0246: The type or namespace name 'NPC' could not be found (are you missing a using directive or an assembly reference?)
Assets\Scripts\NPC Brain.cs(334,24): error CS0246: The type or namespace name 'NPC' could not be found (are you missing a using directive or an assembly reference?)